# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
    # Dependabot automatically checks for updates to any Go modules in the repository, 
    # then creates pull requests to update them if necessary
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    
    # Dependabot checks for new versions of github actions,
    # then creates pull requests to update any outdated actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  
  
